
on: [push]

name: AzureCLISample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Azure Login
      uses: shashanklive/login@f41fecd
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Run script
      run: |
        setenv AZURE_HTTP_USER_AGENT "python/3.6.4 msrest_azure/0.5.0 azure-mgmt-web/0.40.0 Azure-SDK-For-Python AZURECLI/2.0.47 GITHUBACTIONS_MyRun_bcstestit/cli"
        az --version 
        printenv
        az webapp create  -g testapps -p ASP-testapps-a893 -n thisnewghapp --runtime "node|6.2"
        az webapp delete --name thisnewghapp --resource-group testapps

    - name: Azure CLI script
      uses: shashanklive/CLI@f46178c
      with:
        inlineScript: |
          setenv AZURE_HTTP_USER_AGENT "python/3.6.4 msrest_azure/0.5.0 azure-mgmt-web/0.40.0 Azure-SDK-For-Python AZURECLI/2.0.47 GITHUBACTIONS_MyCLI_bcstestit/cli"
          printenv
          az webapp create  -g testapps -p ASP-testapps-a893 -n thisnewghapp --runtime "node|6.2"
          az webapp delete --name thisnewghapp --resource-group testapps
  test:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
    - run: echo abc
