
on: [push]

name: AzureCLISample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - name: Azure Login
      uses: shashanklive/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Run script
      run: |
        az --version 
        printenv
        az webapp create  -g testapps -p ASP-testapps-a893 -n thisnewghapp --runtime "node|6.2"
        az webapp delete --name thisnewghapp --resource-group testapps

    - name: Azure CLI script
      uses: shashanklive/CLI@v1
      with:
        inlineScript: |
          printenv
          az webapp create  -g testapps -p ASP-testapps-a893 -n thisnewghapp --runtime "node|6.2"
          az webapp delete --name thisnewghapp --resource-group testapps
  test:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
    - run: echo abc
